FROM python:3.10-slim

WORKDIR /app

COPY ./admin_portal_backend_service/requirements.txt ./admin_portal_backend_service/requirements.txt

RUN pip install --no-cache-dir --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org -r ./admin_portal_backend_service/requirements.txt

COPY ./admin_portal_backend_service/ /app/admin_portal_backend_service/

EXPOSE 8002

CMD ["uvicorn", "admin_portal_backend_service.main:app", "--host", "0.0.0.0", "--port", "8002"]
