services:
  user-service:
    build:
      context: .
      dockerfile: dockerfile.user_service
    container_name: user-service-compose
    ports:
      - "8001:8001"
    volumes:
      - ./user_service:/app/user_service
    networks:
      - ocr_network
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: dockerfile.apigw_service
    container_name: api-gateway-compose
    ports:
      - "8000:8000"
    volumes:
      - ./api_gateway:/app/api_gateway
    environment:
      - USER_SERVICE_URL=http://user-service-compose:8001
      # - STORAGE_SERVICE_URL=http://storage-service-compose:8003
      # - ADMIN_PORTAL_BACKEND_URL=http://admin-portal-backend-compose:8002
    depends_on:
      - user-service
    networks:
      - ocr_network
    restart: unless-stopped

  admin-portal-backend:
    build:
      context: .
      dockerfile: dockerfile.admin_portal_service
    container_name: admin-portal-backend-compose
    ports:
      - "8002:8002"
    volumes:
      - ./admin_portal_backend_service:/app/admin_portal_backend_service
    environment:
      - USER_SERVICE_URL=http://user-service-compose:8001
    depends_on:
      - user-service
    networks:
      - ocr_network
    restart: unless-stopped

  storage-service:
    build:
      context: .
      dockerfile: dockerfile.storage_service
    container_name: storage-service-compose
    ports:
      - "8003:8003"
    volumes:
      - ./storage_service/uploads:/app/storage_service/uploads
      - ./storage_service:/app/storage_service
    networks:
      - ocr_network
    restart: unless-stopped

  admin-portal-frontend:
    build:
      context: .
      dockerfile: dockerfile.admin_portal_frontend # Sử dụng Dockerfile mới cho Python/FastAPI frontend
    container_name: admin-portal-frontend-py-compose
    ports:
      - "8080:8080" # FastAPI frontend sẽ chạy trên port 8080 bên trong container
    volumes:
      - ./admin_portal_frontend:/app/admin_portal_frontend # Mount code frontend
    environment:
      # ADMIN_PORTAL_BACKEND_URL sẽ được pydantic-settings trong admin_portal_frontend/config.py đọc
      - ADMIN_PORTAL_BACKEND_URL=http://admin-portal-backend-compose:8002
    depends_on:
      - admin-portal-backend # Frontend này phụ thuộc vào backend của nó
    networks:
      - ocr_network
    restart: unless-stopped

networks:
  ocr_network:
    driver: bridge
