FROM python:3.10-slim

WORKDIR /app

COPY ./storage_service/requirements.txt ./storage_service/requirements.txt

RUN pip install --no-cache-dir --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org -r ./storage_service/requirements.txt

COPY ./storage_service/ /app/storage_service/

EXPOSE 8003

CMD ["uvicorn", "storage_service.main:app", "--host", "0.0.0.0", "--port", "8003"]
