FROM python:3.10-slim

WORKDIR /app

COPY ./admin_portal_frontend/requirements.txt ./admin_portal_frontend/requirements.txt

RUN pip install --no-cache-dir --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org -r ./admin_portal_frontend/requirements.txt

COPY ./admin_portal_frontend/ /app/admin_portal_frontend/

EXPOSE 8080

CMD ["uvicorn", "admin_portal_frontend.main:app", "--host", "0.0.0.0", "--port", "8080"]
