services:
  user-service:
    build:
      context: .
      dockerfile: dockerfile.user_service
    container_name: user-service-compose
    ports:
      - "8001:8001"
    volumes:
      - ./user_service:/app/user_service
    networks:
      - ocr_network
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: dockerfile.apigw_service
    container_name: api-gateway-compose
    ports:
      - "8000:8000"
    volumes:
      - ./api_gateway:/app/api_gateway
    environment:
      - USER_SERVICE_URL=http://user-service-compose:8001
      # - STORAGE_SERVICE_URL=http://storage-service-compose:8003
      # - ADMIN_PORTAL_BACKEND_URL=http://admin-portal-backend-compose:8002
    depends_on:
      - user-service
    networks:
      - ocr_network
    restart: unless-stopped

  admin-portal-backend:
    build:
      context: .
      dockerfile: dockerfile.admin_portal_service
    container_name: admin-portal-backend-compose
    ports:
      - "8002:8002"
    volumes:
      - ./admin_portal_backend_service:/app/admin_portal_backend_service
    environment:
      - USER_SERVICE_URL=http://user-service-compose:8001
    depends_on:
      - user-service
    networks:
      - ocr_network
    restart: unless-stopped

  storage-service:
    build:
      context: .
      dockerfile: dockerfile.storage_service
    container_name: storage-service-compose
    ports:
      - "8003:8003"
    volumes:
      - ./storage_service/uploads:/app/storage_service/uploads
      - ./storage_service:/app/storage_service
    networks:
      - ocr_network
    restart: unless-stopped

  admin-portal-frontend:
    build:
      context: .
      dockerfile: dockerfile.admin_portal_frontend # Sử dụng Dockerfile mới tạo
    container_name: admin-portal-frontend-compose
    ports:
      - "8080:80" # Map cổng 80 của Nginx trong container ra cổng 8080 trên máy host
    volumes:
      - ./admin_portal_frontend:/usr/share/nginx/html # Mount code frontend để thay đổi được phản ánh
    depends_on: # Frontend này phụ thuộc vào backend của nó
      - admin-portal-backend
    networks:
      - ocr_network
    restart: unless-stopped

networks:
  ocr_network:
    driver: bridge
