FROM python:3.10-slim

WORKDIR /app

COPY ./user_service/requirements.txt ./user_service/requirements.txt

RUN pip install --no-cache-dir --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org -r ./user_service/requirements.txt

COPY ./user_service/ /app/user_service/

EXPOSE 8001

CMD ["uvicorn", "user_service.main:app", "--host", "0.0.0.0", "--port", "8001"]
